[google_service_account]
type = "service_account"
project_id = "phl-llm"
private_key_id = "445554fe8be84e851d1e6f8ae5909fff0022df43"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCsaEu/q/93oK3x
f+CXk26JQgu+2B9tN9iYz+IRmTksYbTVUuZQc5SXBS2GPBJoSb1AK3Fh1P0MYfQK
PElJBoQivk1RggHxTTVn2RNhlO79FyQob1zipNjvpjBRbV8x2TC1xL0uo0WjTbLa
XMa21WwHSo8vsqs0LzELgXsvSZFN29t9U+iy6OiuvkX2Xbm31ruBSyS6dxvxpXNb
DT81J7qmCVYIk8EvwvDNRfGZDL7IgqsO08d3iFrM8oltl1Akk8Zm8lvQf79L/ypd
MhuNrvMeZUEj0ggSgm+osIGizmFWRhnSatlPihra6JQcHksDfktZhOhF+YzFs7E3
PflKRkY7AgMBAAECggEAAtV9GLHTiMoIMStQHLYbwtHHy7Fbz6XzkcMXTpNeIAG0
9ORvmMlgP68oRWNJQVDhXSO8t9VedRdjMlTsKmsO1eGOljtIleQWLHsJ0a90AuQB
wDgdvCe1lFAFL3KblKrTr5mWN4y6UT2ojXbyg6I9peWCl1vo8PQnQAQkoidIcmD+
YHdjtwQOODIrjnECMh29bRV5IOgn3tDu32mK20WsZ4DmfvbCBDN7oYvcG+U24buS
O1wR0eRCiIXDlmFRXn82vgF/1GOV/K1tZNEDCymeeU2UQr0soEfS1TP4fV3LL6NY
+X9PRl3400FA6uEMBytJAaAUBjCmHiIVE9K9RIx9sQKBgQDdWSVROuXyfHv7TAfa
816aUbAFgw33zj3WM3olC2SqaSAHI2U9dIIbYbu7uEviR7lfkjemyHLWrOUQYZWU
FogF7lEguQFPaOoYBSMFvhm0S8Mb5EirUOrwhiWeI7xvxRR9yDKHVFWD4N6FoXl+
AfGynAd9JqGVUbmjcbHwyYKcawKBgQDHZcZttNKXZcj5KZZW+NsS5Vm+Q/GWfq6w
7T4zdY/VMvRL2ut7dqNI3FSOu+1hlRwpB0qaWm501n03bJQuG/kuh+2urdOdchI1
bawuY0KK79bRhJBMGSVHOgwyriyXkDIUpoq43Y+GqsjljnvY16OPi2D5Q2ge8RGu
zmOM9rxxcQKBgGY0hHOmg4jdDA50A+iImXUeJO3Wnrt+orTmXg7+3MOG+P/yywt+
YZktHpdGONvKDIFhrYq4YbZYbQiMVpnjcXlzmkhGxKEbK4Rd0tcS+SF0Hioh1aAt
I95dwr7rd1YQpS6TIymzuizDx1vivIt/cE/tldOm49NjwhkDJYuuMD3zAoGAA0bb
5O+kylIk5FtXmiRKzVuxhtvs+3Eng8bST9wtue41b42wcv33Hvpn9VSHSSQ/Kzlw
c2rrB8aClkeVg9B33tjjAgzfPmYigHhF7Rk6fbgFSron+Ogs4afFjYupNfBrskUu
YG1br3XdCVC3HlAk4vYCaPY/nsqNZNcFccqYPDECgYA66TcWvdHW1XFEvbKfZjvK
CbBSixf0W8M9exI21sM6WHqXOLBgrWCWHPzE0+2K9Uogtd1EtZNAIlOjvCXEbcRl
WT2AE9LKa6Fi6h+AZswkOhGO3GPWS65N+TO1Qs1wKK0bqQL0lNN4/8DzY52AI6rA
I6ZlOh/872wrFmWx5PCYLg==
-----END PRIVATE KEY-----"""
client_email = "service-account-phl-llm@phl-llm.iam.gserviceaccount.com"
client_id = "110719801019346760813"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-account-phl-llm%40phl-llm.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

